# Generated by Django 3.1.5 on 2021-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('production_companies', models.TextField()),
                ('revenue', models.FloatField()),
                ('rating', models.FloatField()),
                ('ratio', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('wiki_url', models.CharField(max_length=1000)),
                ('wiki_abstract', models.TextField(max_length=255)),
                ('year', models.CharField(max_length=255)),
            ],
        ),
    ]
