# Generated by Django 3.1.5 on 2021-01-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(blank=True, null=True)),
                ('production_companies', models.TextField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('wiki_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('wiki_abstract', models.TextField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
