# Generated by Django 3.1.5 on 2021-01-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_link', '0002_auto_20210110_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
